# Generated by Django 3.2.7 on 2021-10-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diabetes', '0001_initial'),
        ('heart', '0001_initial'),
        ('kidney', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diabetes',
            field=models.ManyToManyField(blank=True, null=True, related_name='diabetes_data', to='Diabetes.Diabets'),
        ),
        migrations.AddField(
            model_name='profile',
            name='heart',
            field=models.ManyToManyField(blank=True, null=True, related_name='heart_data', to='heart.Heart'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kidney',
            field=models.ManyToManyField(blank=True, null=True, related_name='kidney_data', to='kidney.Kidney'),
        ),
    ]
