# Generated by Django 3.2.7 on 2021-10-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('age', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cp', models.DecimalField(decimal_places=2, max_digits=20)),
                ('trestbps', models.DecimalField(decimal_places=2, max_digits=20)),
                ('chol', models.DecimalField(decimal_places=2, max_digits=20)),
                ('thalach', models.DecimalField(decimal_places=2, max_digits=20)),
                ('exang', models.DecimalField(decimal_places=2, max_digits=20)),
                ('oldpeak', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ca', models.DecimalField(decimal_places=2, max_digits=20)),
                ('result', models.IntegerField(blank=True, default=0, null=True)),
                ('result2', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
